### ISSUE TITLE
Install on Jessie errors

### ISSUE THREAD

**Issue by SailingGreg** [piface/PiFace-Real-Time-Clock#6]
The following is from an install on Jessie which appears to have a problem - is this terminal?

pi@raspberrypi ~/startTimer $  sudo apt-get install i2c-tools
Reading package lists... Done
Building dependency tree
Reading state information... Done
Suggested packages:
  libi2c-dev python-smbus
The following NEW packages will be installed:
  i2c-tools
0 upgraded, 1 newly installed, 0 to remove and 1 not upgraded.
Need to get 51.3 kB of archives.
After this operation, 227 kB of additional disk space will be used.
Get:1 http://archive.raspberrypi.org/debian/ jessie/main i2c-tools armhf 3.1.1+svn-2 [51.3 kB]
Fetched 51.3 kB in 0s (140 kB/s)
Selecting previously unselected package i2c-tools.
(Reading database ... 117146 files and directories currently installed.)
Preparing to unpack .../i2c-tools_3.1.1+svn-2_armhf.deb ...
Unpacking i2c-tools (3.1.1+svn-2) ...
Processing triggers for man-db (2.7.0.2-5) ...
Setting up i2c-tools (3.1.1+svn-2) ...
/run/udev or .udevdb or .udev presence implies active udev.  Aborting MAKEDEV invocation.

**Comment by tompreston** [comment]
Hi,
Sorry for taking so long to get back to you. I just tested this on a Raspberry Pi 3 (Jessie) and I'm getting the same message. Fortunately, `i2c-tools` is installed anyway:

```
$ dpkg --status i2c-tools
Package: i2c-tools
Status: install ok installed
Priority: extra
Section: utils
Installed-Size: 222
Maintainer: Aurelien Jarno <aurel32@debian.org>
Architecture: armhf
Version: 3.1.1+svn-2
Depends: libc6 (>= 2.7), perl, adduser, udev | makedev
Suggests: libi2c-dev, python-smbus
Conflicts: lm-sensors (<< 1:3.0.0-1)
Description: heterogeneous set of I2C tools for Linux
 This package contains a heterogeneous set of I2C tools for Linux: a bus
 probing tool, a chip dumper, register-level access helpers, EEPROM
 decoding scripts, and more.
Homepage: http://www.lm-sensors.org
```

So you can follow the [(new!) instructions in the README](https://github.com/piface/PiFace-Real-Time-Clock#install) and it should work now.
